---

# Check if installed

- name: check if already installed (debian)
  command: dpkg-query -W zabbix-release
  register: zabbix_release_check_deb
  failed_when: zabbix_release_check_deb.rc > 1
  changed_when: zabbix_release_check_deb.rc == 1
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

# Install repos Debian/Ubuntu

- name: Download zabbix-release(Debian 10)
  get_url:
    url="{{ repo_deb_10 }}"
    dest='/tmp/zabbix-release.deb'
  when:
    - zabbix_release_check_deb.rc == 1
    - ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == '10'

- name: Download zabbix-release(Debian 9) 
  get_url:
    url="{{ repo_deb_9 }}"
    dest='/tmp/zabbix-release.deb'
  when:
    - zabbix_release_check_deb.rc == 1
    - ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == '9'


- name: Download zabbix-release(Debian 8) 
  get_url:
    url="{{ repo_deb_8 }}"
    dest='/tmp/zabbix-release.deb'
  when:
    - zabbix_release_check_deb.rc == 1
    - ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == '8'

- name: Download zabbix-release(Debian 7)
  get_url:
    url="{{ repo_deb_7 }}"
    dest='/tmp/zabbix-release.deb'
  when:
    - zabbix_release_check_deb.rc == 1
    - ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == '7'
    

- name: Download zabbix-release(Ubuntu 18.xx) 
  get_url:
    url="{{ repo_ubuntu_18 }}"
    dest='/tmp/zabbix-release.deb'
  when:
    - zabbix_release_check_deb.rc == 1
    - ansible_facts['distribution'] == 'Ubuntu' and {{ ansible_distribution_version }} >= 18


- name: Download zabbix-release(Ubuntu 16.xx)
  get_url:
    url="{{ repo_ubuntu_16 }}"
    dest='/tmp/zabbix-release.deb'
  when:
    - zabbix_release_check_deb.rc == 1
    - ansible_facts['distribution'] == 'Ubuntu' and ansible_distribution_version >= 16

- name: Download zabbix-release(Ubuntu 14.xx)
  get_url:
    url="{{ repo_ubuntu_14 }}"
    dest='/tmp/zabbix-release.deb'
  when:
    - zabbix_release_check_deb.rc == 1
    - ansible_facts['distribution'] == 'Ubuntu' and ansible_distribution_version >= 14




- name: Install zabbix-release
  become: yes
  apt:
    deb='/tmp/zabbix-release.deb'
  when:
    - zabbix_release_check_deb.rc == 1
    - ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

# Install agent 2 Debian/Ubuntu
- name: remove old agent
  apt:
    name:
      - zabbix-agent
    state: absent
  become: yes
  when: 
    - ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] != '8'
    - ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] != '7'


- name: Install Zabbix-agent2 (Debian/Ubuntu)
  apt:
    name:
      - zabbix-agent2
    state: present
    update_cache: yes
  become: yes
  when: 
    - ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'
    - not (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == '8')
    - not (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == '7')

- name: Install Zabbix-agent (Debian/Ubuntu old)
  apt:
    name:
      - zabbix-agent
    state: present
    update_cache: yes
  become: yes
  when: (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == '8') or
        (ansible_facts['distribution'] == 'Debian' and ansible_facts['distribution_major_version'] == '7')